---
- name: Crear grupo GProfesores
  ansible.builtin.group:
    name: GProfesores
    state: present

- name: Crear grupo GAlumnos
  ansible.builtin.group:
    name: GAlumnos
    state: present

- name: Crear usuario profesor
  ansible.builtin.user:
    name: profesor
    groups: GProfesores
    state: present

- name: Crear usuario alumno
  ansible.builtin.user:
    name: alumno
    groups: GAlumnos
    state: present



