---
- name: Cambiar propietario de /UTN/Alumno
  ansible.builtin.file:
    path: /UTN/Alumno
    owner: alumno
    state: directory

- name: Cambiar propietario de /UTN/Profesor
  ansible.builtin.file:
    path: /UTN/Profesor
    owner: profesor
    state: directory

